# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build the application
FROM node:16-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Run the application
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy the build from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

# Environment variables required by the application
ENV SUPABASE_URL=your_project_url_here
ENV SUPABASE_KEY=your_service_role_key_here
ENV SUPABASE_ACCESS_TOKEN=your_access_token_here

# Expose the necessary port
EXPOSE 3000

# Run the application
ENTRYPOINT ["node", "build/index.js"]