# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build the application
FROM node:16-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Run the application
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy the build from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

# Environment variables required by the application
ENV SUPABASE_URL=https://pkvnfcxdodzwbvcxkmxj.supabase.co
ENV SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrdm5mY3hkb2R6d2J2Y3hrbXhqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTI4MzI5OSwiZXhwIjoyMDY2ODU5Mjk5fQ.TnW_d3ekcNi3uNaWrympT37qjvG2V_p0pl-MdpCffWs
ENV SUPABASE_ACCESS_TOKEN=sbp_59f678d2cbe7369517656b373b03744f37501449

# Expose the necessary port
EXPOSE 3000

# Run the application
ENTRYPOINT ["node", "build/index.js"]
